## Configuration file for BCE applied on ODIR case / control

XP_NAME:
  xp_name : "odir_subtype_BinaryClassification"

#############################################
########### DATASET CONFIG ##################
#############################################
DATASET_CONFIG:
  ROOT:
    input_path: "/home/ids/rlouiset/odir_5k/"
    metadata_path: "/home/ids/rlouiset/odir_5k/"
  DATA_DIRS:
    input_path:
      train_val :
        - "X_train.npy" # TRAIN dataset
        - "X_test.npy" # VAL dataset
      test : "X_test.npy" # TEST dataset
    metadata_path:
      train_val :
        - "y_train.csv" # TRAIN metadata .csv
        - "y_test.csv" # VAL metadata .csv
      test : "y_test.csv" # TEST metadata .csv

#############################################
######## FEATURES AND LABELS CONFIG #########
#############################################
LABELS_DICT:
  nb_folds: 3
  labels: ['subtype', 'diagnosis']

#############################################
######## TRAINING CONFIG #########
#############################################
COMPUTATION_DICT:
  pin_mem: False
  cuda: True
  gpus: 1
  num_cpu_workers: 8
  persistent_workers: True

MODEL_CONFIG:
  pretrained_path: ~
  n_classes: 2
  n_clusters: 5
  model_type: 'Classification'

LOSS_CONFIG:
  loss: 'CrossEntropy'
  loss_params:
    scaler: 'standard'
    class_weights: ~

OPTIMIZER_CONFIG:
  lr: 0.00002

TRAINING_CONFIG:
  self_supervision: ~
  data_augmentation:
    vertical_flip :
      p : 0.5
    gaussian_blur :
      kernel_size : 5
    random_affine :
      degrees : 45
      translate :
        - 0.05
        - 0.05

  batch_size: 256
  min_epochs: 50
  max_epochs: 50
  drop_last: False
  reload_dataloader: True

#############################################
########### METRICS_CONFIG ##################
#############################################
METRICS_CONFIG:
  checkpoint_dir: "/home/ids/rlouiset/records/"