## CONFIGURATION FILE FOR DEEP UCSL FOR ODIR 5K

XP_NAME:
  xp_name : "odir_5k_subtype_DeepUCSL"

#############################################
########### DATASET CONFIG ##################
#############################################
DATASET_CONFIG:
  ROOT:
    input_path: "/home/ids/rlouiset/odir_5k/"
    metadata_path: "/home/ids/rlouiset/odir_5k/"
  DATA_DIRS:
    input_path:
      train_val :
        - "X_train.npy" # TRAIN dataset
        - "X_test.npy" # VAL dataset
      test : "X_test.npy" # TEST dataset
    metadata_path:
      train_val :
        - "y_train.csv" # TRAIN metadata
        - "y_test.csv" # VAL metadata
      test : "y_test.csv" # TEST metadata

#############################################
######## FEATURES AND LABELS CONFIG #########
#############################################
# input data configurations
LABELS_DICT:
  nb_folds: 3
  labels: ['subtype', 'diagnosis']

#############################################
######## TRAINING CONFIG #########
#############################################
COMPUTATION_DICT:
  pin_mem: False
  cuda: True
  gpus: 1
  num_cpu_workers: 8
  persistent_workers: True

MODEL_CONFIG:
  pretrained_path: ~
  n_classes: 2
  n_clusters: 5
  model_type: 'Deep UCSL'

LOSS_CONFIG:
  loss: 'DeepUCSL'
  loss_params:
    scaler: "standard"
    clustering_weight: 1
    conditional_classification_weight: 1
    pseudo_labels_confidence: "linear"
    max_confidence_epoch: 50
    class_weights:
      - 0.5
      - 0.5

OPTIMIZER_CONFIG:
  lr: 0.000005

TRAINING_CONFIG:
  self_supervision: ~
  data_augmentation :
    vertical_flip :
      p : 0.5
    gaussian_blur :
      kernel_size : 5
    random_affine :
      degrees : 45
      translate :
        - 0.05
        - 0.05
  batch_size: 256
  min_epochs: 50
  max_epochs: 50
  drop_last: False
  reload_dataloader: True

#############################################
########### METRICS_CONFIG ##################
#############################################
METRICS_CONFIG:
  checkpoint_dir: "/tsi/clusterhome/rlouiset/records/"
