## Configuration file for PCL applied on RETINAL OCT

XP_NAME:
  xp_name : "retinal_OCT_subtype_PCL"

#############################################
########### DATASET CONFIG ##################
#############################################
DATASET_CONFIG:
  ROOT:
    input_path: "/home/ids/rlouiset/retinal_OCT/"
    metadata_path: "/home/ids/rlouiset/retinal_OCT/"
  DATA_DIRS:
    input_path:
      train_val :
        - "X_train_disease.npy" # TRAIN dataset
        - "X_test_disease.npy" # VAL dataset
      test : "X_test_disease.npy" # TEST dataset
    metadata_path:
      train_val :
        - "y_train_disease.csv" # TRAIN metadata .csv
        - "y_test_disease.csv" # VAL metadata .csv
      test : "y_test_disease.csv" # TEST metadata .csv

#############################################
######## FEATURES AND LABELS CONFIG #########
#############################################
LABELS_DICT:
  nb_folds: 3
  labels: ['subtype', 'diagnosis']

#############################################
######## TRAINING CONFIG #########
#############################################
COMPUTATION_DICT:
  pin_mem: False
  cuda: True
  gpus: 1
  num_cpu_workers: 16
  persistent_workers: True

MODEL_CONFIG:
  pretrained_path: ~
  n_classes: ~
  n_clusters: 3
  model_type: 'PCL'

LOSS_CONFIG:
  loss: 'PCL'
  loss_params:
    scaler: "standard"
    temperature: 0.1
    pre_training_epochs: 30

OPTIMIZER_CONFIG:
  lr: 0.00001

TRAINING_CONFIG:
  self_supervision: 'PCL'
  data_augmentation :
    random_resized_crop :
      size : 224
      scale:
        - 0.75
        - 1
    horizontal_flip:
      p : 0.5
    gaussian_blur:
      kernel_size: 3
    random_affine:
      degrees: 25
      translate:
        - 0.1
        - 0.1

  batch_size: 256
  min_epochs: 50
  max_epochs: 50
  drop_last: False
  reload_dataloader: True

#############################################
########### METRICS_CONFIG ##################
#############################################
METRICS_CONFIG:
  checkpoint_dir: "/home/ids/rlouiset/records/"