## CONFIGURATION FILE FOR VAE [SCHIZOPHRENIA+BIPOLAR DISORDER] - HEALTHY CONTROL

XP_NAME:
  xp_name : "HC_MD_VAE"

#############################################
########### DATASET CONFIG ##################
#############################################
DATASET_CONFIG:
  ROOT:
    input_path: "/data1/rlouiset/psy/" # "/neurospin/psy_sbox/rl264746/"
    metadata_path: "/data1/rlouiset/psy/" # "/neurospin/psy_sbox/rl264746/"
  DATA_DIRS:
    input_path:
      - "bsnip1_cat12vbm_mwp1-gs.npy"
      - "biobd_cat12vbm_mwp1-gs.npy"
      - "schizconnect-vip-prague_cat12vbm_mwp1-gs.npy"
    metadata_path:
      - "bsnip1_cat12vbm_participants.csv"
      - "biobd_cat12vbm_participants.csv"
      - "schizconnect-vip-prague_cat12vbm_participants.csv"

    #input_path:
    #  - "psy_sbox/bd261576/Datasets/bsnip_mwp1_gs_data-32.npy"
    #  - "psy_sbox/bd261576/Datasets/schizconnect-vip_mwp1_gs_data-32.npy"
    #  - "psy_sbox/bd261576/Datasets/biobd_mwp1_gs_data-32.npy"
    #metadata_path:
    #  - "psy_sbox/bd261576/Datasets/bsnip_mwp1_gs_participants.csv"
    #  - "psy_sbox/bd261576/Datasets/schizconnect-vip_mwp1_gs_participants.csv"
    #  - "psy_sbox/bd261576/Datasets/biobd_mwp1_gs_participants.csv""""

#############################################
######## FEATURES AND LABELS CONFIG #########
#############################################
LABELS_DICT:
  preproc: "cat12"
  sep: ","
  train_size: 0.9
  nb_folds: 5
  db: "clustering_bip_skz"
  labels: ['diagnosis']
  stratify_label: ['diagnosis']
  self_supervision: ~
  labels_mapping:
    diagnosis :
      control: 0
      schizophrenia: 1
      bipolar disorder: 2
      psychotic bipolar disorder: 2

#############################################
######## TRAINING CONFIG #########
#############################################
COMPUTATION_DICT:
  pin_mem: False
  cuda: True
  gpus: 1
  num_cpu_workers: 16
  persistent_workers: True

MODEL_CONFIG:
  pretrained_path: ~
  n_classes: 2
  n_clusters: 2
  model_type: 'VAE'
  net: 'VAE'

LOSS_CONFIG:
  loss: 'VAE'
  loss_params:
    beta: 1

OPTIMIZER_CONFIG:
  lr: 0.0001

TRAINING_CONFIG:
  batch_size: 8
  min_epochs: 100
  max_epochs: 100
  drop_last: False
  reload_dataloader: True

#############################################
########### METRICS_CONFIG ##################
#############################################
METRICS_CONFIG:
  checkpoint_dir:  "/data1/rlouiset/records/"
